site_name: 《剑指 Offer》（第 2 版）
theme: readthedocs
# theme: material
# theme: bootstrap
# theme: amelia
# theme: cerulean
# theme: cosmo
# theme: cyborg

# 下面这个主题不错
# theme: flatly
# theme: united

nav:
  - 首页: index.md
  - 第 1 - 20 题:
    - 剑指 Offer 03. 数组中重复的数字: 03.md
    - 剑指 Offer 04. 二维数组中的查找: 04.md
    - 剑指 Offer 05. 替换空格: 05.md
    - 剑指 Offer 06. 从尾到头打印链表: 06.md
    - 剑指 Offer 07. 重建二叉树: 07.md
    - 剑指 Offer 08. 二叉树的下一个结点: 08.md
    - 剑指 Offer 09. 用两个栈实现队列: 09.md
    - 剑指 Offer 10- I. 斐波那契数列: 10-1.md
    - 剑指 Offer 10- II. 青蛙跳台阶问题: 10-2.md
    - 剑指 Offer 11. 旋转数组的最小数字: 11.md
    - 剑指 Offer 12. 矩阵中的路径: 12.md
    - 剑指 Offer 13. 机器人的运动范围: 13.md
    - 剑指 Offer 14- I. 剪绳子: 14-1.md
    - 剑指 Offer 14- II. 剪绳子 II: 14-2.md
    - 剑指 Offer 15. 二进制中1的个数: 15.md
    - 剑指 Offer 16. 数值的整数次方: 16.md
    - 剑指 Offer 17. 打印从1到最大的n位数: 17.md
    - 剑指 Offer 18. 删除链表的节点: 18.md
    - 剑指 Offer 19. 正则表达式匹配: 19.md
    - 剑指 Offer 20. 表示数值的字符串: 20.md
  - 第 21 - 40 题:
    - 剑指 Offer 21. 调整数组顺序使奇数位于偶数前面: 21.md
    - 剑指 Offer 22. 链表中倒数第k个节点: 22.md
    - 剑指 Offer 24. 反转链表: 24.md
    - 剑指 Offer 25. 合并两个排序的链表: 25.md
    - 剑指 Offer 26. 树的子结构: 26.md
    - 剑指 Offer 27. 二叉树的镜像: 27.md
    - 剑指 Offer 28. 对称的二叉树: 28.md
    - 剑指 Offer 29. 顺时针打印矩阵: 29.md
    - 剑指 Offer 30. 包含min函数的栈: 30.md
    - 剑指 Offer 31. 栈的压入、弹出序列: 31.md
    - 剑指 Offer 32 - I. 从上到下打印二叉树: 32-1.md
    - 剑指 Offer 32 - II. 从上到下打印二叉树 II: 32-2.md
    - 剑指 Offer 32 - III. 从上到下打印二叉树 III: 32-3.md
    - 剑指 Offer 33. 二叉搜索树的后序遍历序列: 33.md
    - 剑指 Offer 34. 二叉树中和为某一值的路径: 34.md
    - 剑指 Offer 35. 复杂链表的复制: 35.md
    - 剑指 Offer 36. 二叉搜索树与双向链表: 36.md
    - 剑指 Offer 37. 序列化二叉树: 37.md
    - 剑指 Offer 38. 字符串的排列: 38.md
    - 剑指 Offer 39. 数组中出现次数超过一半的数字: 39.md
    - 剑指 Offer 40. 最小的k个数: 40.md
  - 第 41 - 60 题:
    - 剑指 Offer 41. 数据流中的中位数: 41.md
    - 剑指 Offer 42. 连续子数组的最大和: 42.md
    - 剑指 Offer 43. 1～n 整数中 1 出现的次数: 43.md
    - 剑指 Offer 44. 数字序列中某一位的数字: 44.md
    - 剑指 Offer 45. 把数组排成最小的数: 45.md
    - 剑指 Offer 46. 把数字翻译成字符串: 46.md
    - 剑指 Offer 47. 礼物的最大价值: 47.md
    - 剑指 Offer 48. 最长不含重复字符的子字符串: 48.md
    - 剑指 Offer 49. 丑数: 49.md
    - 剑指 Offer 50. 第一个只出现一次的字符: 50.md
    - 剑指 Offer 51. 数组中的逆序对: 51.md
    - 剑指 Offer 52. 两个链表的第一个公共节点: 52.md
    - 剑指 Offer 53 - I. 在排序数组中查找数字 I: 53.md
    - 剑指 Offer 53 - II. 0～n-1中缺失的数字: 53-2.md
    - 剑指 Offer 54. 二叉搜索树的第k大节点: 54.md
    - 剑指 Offer 55 - I. 二叉树的深度: 55.md
    - 剑指 Offer 55 - II. 平衡二叉树: 55-2.md
    - 剑指 Offer 56 - I. 数组中数字出现的次数: 56.md
    - 剑指 Offer 56 - II. 数组中数字出现的次数 II: 56-2.md
    - 剑指 Offer 57. 和为s的两个数字: 57.md
    - 剑指 Offer 57 - II. 和为s的连续正数序列: 57-2.md
    - 剑指 Offer 58 - I. 翻转单词顺序: 58.md
    - 剑指 Offer 58 - II. 左旋转字符串: 58-2.md
    - 剑指 Offer 59 - I. 滑动窗口的最大值: 59.md
    - 剑指 Offer 59 - II. 队列的最大值: 59-2.md
    - 剑指 Offer 60. n个骰子的点数: 60.md
  - 第 61 - 68 题:
    - 剑指 Offer 61. 扑克牌中的顺子: 61.md
    - 剑指 Offer 62. 圆圈中最后剩下的数字: 62.md
    - 剑指 Offer 63. 股票的最大利润: 63.md
    - 剑指 Offer 64. 求1+2+…+n: 64.md
    - 剑指 Offer 65. 不用加减乘除做加法: 65.md
    - 剑指 Offer 66. 构建乘积数组: 66.md
    - 剑指 Offer 67. 把字符串转换成整数: 67.md
    - 剑指 Offer 68 - I. 二叉搜索树的最近公共祖先: 68.md
    - 剑指 Offer 68 - II. 二叉树的最近公共祖先: 68-2.md
  
  #   - 61-n 个骰子的点数: 61-n 个骰子的点数.md
  #   - 62-孩子们的游戏(圆圈中最后剩下的数): 62-孩子们的游戏(圆圈中最后剩下的数).md
  #   - 63-股票的最大利润: 63-股票的最大利润.md
  #   - 64-求1+2+3+...+n: 64-求1+2+3+...+n.md
  #   - 65-不用加减乘除做加法: 65-不用加减乘除做加法.md
  #   - 66-构建乘积数组: 66-构建乘积数组.md
  #   - 67-把字符串转换成整数: 67-把字符串转换成整数.md
  #   - 68-树中两个节点的最近公共祖: 68-树中两个节点的最近公共祖先.md
