site_name: 《剑指 Offer》（第 2 版）
theme: readthedocs
# theme: material
# theme: bootstrap
# theme: amelia
# theme: cerulean
# theme: cosmo
# theme: cyborg

# 下面这个主题不错
# theme: flatly
# theme: united

nav:
  - 首页: index.md
  - 第 1 - 20 题:
    - 3-数组中重复的数字: 03-数组中重复的数字.md
    - 4-二维数组中的查找: 04-二维数组中的查找.md
    - 5-替换空格: 05-替换空格.md
    - 6-从尾到头打印链表: 06-从尾到头打印链表.md
    - 7-重建二叉树: 07-重建二叉树.md
    - 8-二叉树的下一个结点: 08-二叉树的下一个结点.md
    - 9-1-用两个栈实现队列: 09-1-用两个栈实现队列.md
    - 9-2-用队列实现栈: 09-2-用队列实现栈.md
    - 10-1-斐波那契数列: 10-1-斐波那契数列.md
    - 10-1-跳台阶: 10-1-跳台阶.md
    - 10-2-变态跳台阶: 10-2-变态跳台阶.md
    - 10-3-矩形覆盖: 10-3-矩形覆盖.md
    - 11-旋转数组的最小数字: 11-旋转数组的最小数字.md
    - 12-矩阵中的路径: 12-矩阵中的路径.md
    - 13-机器人的运动范围: 13-机器人的运动范围.md
    - 14-剪绳子: 14-剪绳子.md
    - 15-二进制中1的个数: 15-二进制中1的个数.md
    - 16-数值的整数次方: 16-数值的整数次方.md
    - 17-打印从 1 到最大的 n 位数: 17-打印从 1 到最大的 n 位数.md
    - 18-删除链表中重复的结点: 18-删除链表中重复的结点.md
    - 19-正则表达式匹配: 19-正则表达式匹配.md
    - 20-表示数值的字符串: 20-表示数值的字符串.md
  - 第 21 - 40 题:
    - 21-调整数组顺序使奇数位于偶数前面: 21-调整数组顺序使奇数位于偶数前面.md
    - 22-链表中倒数第k个结点: 22-链表中倒数第k个结点.md
    - 23-链表中环的入口结点: 23-链表中环的入口结点.md
    - 24-反转链表: 24-反转链表.md
    - 25-合并两个排序的链表: 25-合并两个排序的链表.md
    - 27-二叉树的镜像: 27-二叉树的镜像.md
    - 28-对称的二叉树: 28-对称的二叉树.md
    - 29-顺时针打印矩阵: 29-顺时针打印矩阵.md
    - 30-包含min函数的栈: 30-包含min函数的栈.md
    - 31-栈的压入、弹出序列: 31-栈的压入、弹出序列.md
    - 32-1-从上往下打印二叉树: 32-1-从上往下打印二叉树.md
    - 32-2-把二叉树打印成多行: 32-2-把二叉树打印成多行.md
    - 32-3-按之字形顺序打印二叉树: 32-3-按之字形顺序打印二叉树.md
    - 33-二叉搜索树的后序遍历序列: 33-二叉搜索树的后序遍历序列.md
    - 34-二叉树中和为某一值的路径: 34-二叉树中和为某一值的路径.md
    - 35-复杂链表的复制: 35-复杂链表的复制.md
    - 36-二叉搜索树与双向链表: 36-二叉搜索树与双向链表.md
    - 37-序列化二叉树: 37-序列化二叉树.md
    - 38-字符串的排列: 38-字符串的排列.md
    - 39-数组中出现次数超过一半的数字: 39-数组中出现次数超过一半的数字.md
    - 40-最小的K个数: 40-最小的K个数.md
  - 第 41 - 60 题:
    - 41-数据流中的中位数: 41-数据流中的中位数.md
    - 42-连续子数组的最大和: 42-连续子数组的最大和.md
    - 44-数字序列中某一位的数字: 44-数字序列中某一位的数字.md
    - 45-把数组排成最小的数: 45-把数组排成最小的数.md
    - 46-把数字翻译成字符串: 46-把数字翻译成字符串.md
    - 47-礼物的最大值: 47-礼物的最大值.md
    - 48-最长不重复字符串的子字符串: 48-最长不重复字符串的子字符串.md
    - 49-丑数: 49-丑数.md
    - 50-2-字符流中第一个不重复的字符: 50-2-字符流中第一个不重复的字符.md
    - 51-数组中的逆序对: 51-数组中的逆序对.md
    - 52-两个链表的第一个公共结点: 52-两个链表的第一个公共结点.md
    - 53-在排序数组中查找数字: 53-在排序数组中查找数字.md
    - 54-二叉搜索树的第k个结点: 54-二叉搜索树的第k个结点.md
    - 55-1-二叉树的深度: 55-1-二叉树的深度.md
    - 55-2-平衡二叉树: 55-2-平衡二叉树.md
    - 56-数字在排序数组中出现的次数: 56-数字在排序数组中出现的次数.md
    - 57-1-滑动窗口的最大值: 57-1-滑动窗口的最大值.md
    - 57-2-队列的最大值: 57-2-队列的最大值.md
    - 58-1-翻转单词序列: 58-1-翻转单词序列.md
    - 58-2-左旋转字符串: 58-2-左旋转字符串.md
  - 第 61 - 68 题:
    - 61-n 个骰子的点数: 61-n 个骰子的点数.md
    - 62-孩子们的游戏(圆圈中最后剩下的数): 62-孩子们的游戏(圆圈中最后剩下的数).md
    - 63-股票的最大利润: 63-股票的最大利润.md
    - 64-求1+2+3+...+n: 64-求1+2+3+...+n.md
    - 65-不用加减乘除做加法: 65-不用加减乘除做加法.md
    - 66-构建乘积数组: 66-构建乘积数组.md
    - 67-把字符串转换成整数: 67-把字符串转换成整数.md
    - 68-树中两个节点的最近公共祖: 68-树中两个节点的最近公共祖先.md
